baseURL = "https://example.com"
languageCode = "en-us"
title = "Vhaos's Leetcode Solutions"
theme = "daily-coding-challenges-theme"
copyright = "Kareem Daggash" # cactus will use title if copyright is not set
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Leetcode Daily"
url = "/leetcodedaily"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "This site hosts some of my solutions to various LeetCode problems, including the hugely popular '[Monthly LeetCoding Challenges](https://leetcode.com/explore/featured/card/september-leetcoding-challenge/)'. I've created this to serve as a visual archive of my progress through solving coding problems. Most solutions here are written primarily in _JavaScript_, however there are also number of solutions in _Java_ and _Python_. You can find the full list of solutions [here](/leetcodedaily)."
  mainSection = "leetcodedaily" # your main section
  homepagepoststitle = "Recently Posted Solutions"
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "Jan 2, 2006" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/vhaos"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/kareemdaggash/"
  [[params.social]]
    name = "email"
    link = "kareemdaggash@gmail.com"  # no need for "mailto:" in the head
